---
name: ".NET Core CLR"
desc: Contains the .NET Core foundational libraries, called CoreFX. It includes classes
  for collections, file systems, console, XML, async and many others.
site: https://github.com/dotnet/coreclr
tags:
- ".NET"
upforgrabs:
  name: up for grabs
  link: https://github.com/dotnet/coreclr/labels/up-for-grabs
